FROM eclipse-temurin:17-jdk-alpine
RUN apk add --no-cache git  maven

WORKDIR /app
RUN git clone https://github.com/HusseinOkasha/GymApp.git

WORKDIR /app/GymApp/

RUN mvn clean package -DskipTests
CMD ["java", "-jar","target/GymApp-0.0.1-SNAPSHOT.jar"]

VOLUME /tmp
EXPOSE 8080